# Base image
FROM nvidia/cuda:12.2.0-devel-ubuntu22.04

# Information.
LABEL name="agrilearn"
LABEL description="Python packages developed by Alternative Data team."
LABEL authors="Alternative Data Team"
LABEL contributors="Alex Araujo; Lucimara Bragagnolo; Luis Zeni; Pedro Pimenta; Luis Macedo" 
LABEL email="<alex.araujo@br.experian.com>"

# To run dpkg (behind other tools like apt) without interactive dialog.
ARG DEBIAN_FRONTEND=noninteractive
    
# New user parameters.
ARG USER_NAME=ec2-user
ARG USER_PASSWORD=ec2-user
ARG USER_UID=1000
ARG USER_GID=1000

# Install all required packages and add sudo support.    
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
    gcc \
    vim \
    curl \
    wget \
    unzip \
    sudo \
    make \ 
    git \
    openssh-client \
    python3-pip \
    graphviz \  
    libgomp1 \
    libgl1 \
    libgdal-dev \
    gdal-bin \
    tree \
    python-is-python3
    
       
# Cleanup.
RUN apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Install AWS command line interface.
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip

# Create the user with sudo privilegies.
RUN groupadd --gid $USER_GID $USER_NAME && \
    useradd --uid $USER_UID --gid $USER_GID --create-home $USER_NAME && \
    echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
    adduser $USER_NAME sudo

# Set working directory.
WORKDIR /agrilearn_app

# Give ec2-user permissions for main folder.
RUN chown -R $USER_NAME:$USER_NAME /agrilearn_app   

# No more root user.
USER $USER_NAME

# Remove annoying startup message.
RUN touch ~/.sudo_as_admin_successful

# Bash is now the default shell.
ENV SHELL=/bin/bash

# Update pip.
RUN pip install --upgrade pip

# GDAL variables. See the following link.
# https://mothergeo-py.readthedocs.io/en/latest/development/how-to/gdal-ubuntu-pkg.html
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal 

# Correct version for GDAL.
RUN pip install GDAL==$(gdal-config --version)

# Install poetry for ec2-user.
RUN curl -sSL https://install.python-poetry.org | python3 -

# Some important scripts are installed here.
ENV PATH=$PATH:/home/${USER_NAME}/.local/bin

# Important configuration info.
ENV AGRILEARN_ENV_PATH=/agrilearn_app/agrilearn/.env

# Enable prompt color in .bashrc.
RUN sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /home/$USER_NAME/.bashrc

# Apt-related tools with prompt.
ARG DEBIAN_FRONTEND=dialog
