version: "3.7"

services:
  agrilearn_dev:
    env_file:
        - .env
    image: ${USER_NAME}/${DOCKER_IMAGE_NAME}:${VERSION}_dev
    container_name: ${DOCKER_IMAGE_NAME}
    build:
        context: ../../
        dockerfile: ./.devcontainer/nicksson-freitas/Dockerfile.dev
        shm_size: "12gb"    # When building.
    shm_size: "12gb"        # When running.
    volumes:
        # Agrilearn packages.
        - ${HOST_AGRILEARN}:/agrilearn_app/agrilearn

        # Datasets, trained models, cached folder and ancillary data.
        - ${HOST_DATASETS}:/agrilearn_app/datasets
        - ${HOST_WEIGHTS}:/agrilearn_app/weights
        - ${HOST_CACHE}:/agrilearn_app/cache
        - ${HOST_ANCILLARY_DATA}:/agrilearn_app/ancillary_data

        # SSH keys.
        - ~/.ssh/:/home/${USER_NAME}/.ssh/
    user: ${USER_NAME}
    hostname: ${HOST_NAME}
    command: sleep infinity
    